### ISSUE TITLE
 "sqrt" is not a known member of module (numpy)

### ISSUE THREAD

**Issue by nschloe** [fannheyward/coc-pyright#163]
When running the command-line pyright on
```python
import numpy

numpy.sqrt(5.0)
```
I correctly get
```
No configuration file found.
stubPath /tmp/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
0 errors, 0 warnings, 0 infos
Completed in 0.635sec
```
When using coc-pyright, I get
```
[Pyright (reportGeneralTypeIssues)] [E] "sqrt" is not a known member of module
```
A bug?

**Comment by nschloe** [comment]
Maybe related to https://github.com/microsoft/pyright/issues/753.

**Comment by yaegassy** [comment]
It may have been fixed in the latest version of the "pyright". 

Could you try to update it by running `:CocUpdate`?

No problem in my environment.

Both hover and jump work fine in my environment. No error message is printed.

**Comment by fannheyward** [comment]
What's your numpy version? Pyright needs type stubs to work, latest version of numpy was released with bundled type stub. You can also install manually https://github.com/typeddjango/awesome-python-typing#stub-packages.

**Comment by nschloe** [comment]
The issue still occurs for me, all packages where already upgraded.
```
python3 -c "import numpy; print(numpy.__version__)"
```
```
1.19.4
```
```
Update finished

- ✓ coc-pyright Current version 1.1.89 is up to date.
```

**Comment by fannheyward** [comment]
Please test in a work space folder, not just single file in /tmp.

**Comment by yaegassy** [comment]
If you want to get similar error results, try to run `pyright --lib`. (If you don't have stub installed)

```
... snip
  3:7 - error: "sqrt" is not a known member of module (reportGeneralTypeIssues)
1 error, 0 warnings, 0 infos
... snip
```

Until numpy 1.20 is released, it's best to use a third-party stub. (e.g. `data-science-types`) REF: https://github.com/numpy/numpy/issues/17826#issuecomment-731862373

**Comment by yaegassy** [comment]
@nschloe 

Or you can set the following in `coc-settings.json` and the error will not be displayed
```
{
  // ...snip
  "python.analysis.useLibraryCodeForTypes": false,
  // ...snip
}
```

**Comment by nschloe** [comment]
Indeed, this is fixed in numpy master and will be part of the next release. https://numpy.org/devdocs/release/1.20.0-notes.html#numpy-is-now-typed
